Paths:
  browser_main_page: https://www.google.com
app:
  background: '#2E2E2E'
  geometryX: '450'
  geometryY: '450'
  icon: notepad.ico
  opacity: '0.96'
  resizable: '0'
  title: Fast Using
button_style:
  background: '#404040'
  corner_radius: '15'
  font: helvetica 12
  foreground: white
  padding: '10'
passwd:
  digits: '1234567890'
  letters: qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM
  symbols: '*@_#-+_$'
shortcuts:
  shortcut1: https://github.com/wrgdbtry/WelcomeUtil
  shortcut1_name: Github
  shortcut2: http://soundcloud.com/
  shortcut2_name: Soundcloud
  shortcut3: https://mail.google.com
  shortcut3_name: Gmail
